# -*- coding: utf-8 -*-
"""Streaming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jt-vYJZQn5GDJtoTCDcSeVwngIbmJlNq
"""

for chunk in chain_str.stream({"topic": "AI", "lenght": "1 sentence})
  print(chunk, end ="|")