# -*- coding: utf-8 -*-
"""String + Chat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xm7vEzHeVEF7yRDysWaeXPZAw6wi1kdR

String Prompt Templates
"""

from langchain_core.prompts import PromptTemplate
prompt_template = PromptTemplate.from_template("Write a poetry")

prompt_template.invoke({"topic":"avocado"})

prompt_template

"""Chat Prompt Templates"""

from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant that answers general questions")
    ("user", "Explain...")
])

prompt.invoke({"topic":"AI"})

system_prompt = "You are a helpful assistant that answers general question"
user_prompt = "Explain what AI is"

prompt = PromptTemplate.from_template(template.format(system_prompt= system_prompt, user_prompt = user_prompt))

prompt.invoke({"topic":"AI"})